services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Combina com o WORKDIR /app do Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
